-- phpMyAdmin SQL Dump
-- version 4.1.14
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Mar 25, 2016 at 05:42 PM
-- Server version: 5.6.17
-- PHP Version: 5.5.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `pythonlab`
--

-- --------------------------------------------------------

--
-- Table structure for table `tbl_cnblogs_info`
--

CREATE TABLE IF NOT EXISTS `tbl_cnblogs_info` (
  `id` smallint(5) unsigned NOT NULL AUTO_INCREMENT COMMENT '序号',
  `blog_title` varchar(80) NOT NULL COMMENT '博客标题',
  `blog_desc` varchar(400) NOT NULL COMMENT '博客描述',
  `blog_url` varchar(160) NOT NULL COMMENT '博客链接',
  `blog_post_time` datetime NOT NULL COMMENT '博客发表时间',
  `blog_page_views` int(11) NOT NULL COMMENT '博客阅读数',
  `blog_commentcount` smallint(6) NOT NULL COMMENT '博客评论数',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COMMENT='获取cnblogs信息' AUTO_INCREMENT=116 ;

--
-- Dumping data for table `tbl_cnblogs_info`
--

INSERT INTO `tbl_cnblogs_info` (`id`, `blog_title`, `blog_desc`, `blog_url`, `blog_post_time`, `blog_page_views`, `blog_commentcount`) VALUES
(1, ' CentOS 6.3下配置iSCSI网络存储', ' 摘要: 一、简介iSCSI（internet SCSI）技术由IBM公司研究开发，是一个供硬件设备使用的、可以在IP协议的上层运行的SCSI指令集，这种指令集合可以实现在IP网络上运行SCSI协议，使其能够在诸如高速千兆以太网上进行路由选择。iSCSI技术是一种新储存技术，该技术是将现有SCSI接口与以太网...', ' http://www.cnblogs.com/mchina/p/centos-iscsi-network-storage.html', '2014-07-07 10:55:00', 14779, 2),
(2, ' CentOS 6.4下Squid代理服务器的安装与配置', ' 摘要: 一、简介代理服务器英文全称是Proxy Server，其功能就是代理网络用户去取得网络信息。Squid是一个缓存Internet 数据的软件，其接收用户的下载申请，并自动处理所下载的数据。当一个用户想要下载一个主页时，可以向Squid 发出一个申请，要Squid 代替其进行下载，然后Squid 连接...', ' http://www.cnblogs.com/mchina/p/centos-squid-proxy-server.html', '2014-07-03 14:28:00', 24998, 6),
(3, ' CentOS 6.5下利用Rsyslog+LogAnalyzer+MySQL部署日志服务器', ' 摘要: 一、简介LogAnalyzer 是一款syslog日志和其他网络事件数据的Web前端。它提供了对日志的简单浏览、搜索、基本分析和一些图表报告的功能。数据可以从数据库或一般的syslog文本文件中获取，所以LogAnalyzer不需要改变现有的记录架构。基于当前的日志数据，它可以处理syslog日志消...', ' http://www.cnblogs.com/mchina/p/linux-centos-rsyslog-loganalyzer-mysql-log-server.html', '2014-06-26 09:16:00', 11808, 1),
(4, ' CentOS 6.4下PXE+Kickstart无人值守安装操作系统', ' 摘要: 一、简介1.1 什么是PXEPXE(Pre-boot Execution Environment，预启动执行环境)是由Intel公司开发的最新技术，工作于Client/Server的网络模式，支持工作站通过网络从远端服务器下载映像，并由此支持通过网络启动操作系统，在启动过程中，终端要求服务器分配IP...', ' http://www.cnblogs.com/mchina/p/centos-pxe-kickstart-auto-install-os.html', '2014-06-24 15:10:00', 15005, 0),
(5, ' CentOS 6.3下配置LVM（逻辑卷管理）', ' 摘要: 一、简介LVM是逻辑盘卷管理（Logical Volume Manager）的简称，它是Linux环境下对磁盘分区进行管理的一种机制，LVM是建立在硬盘和分区之上的一个逻辑层，来提高磁盘分区管理的灵活性。LVM的工作原理其实很简单，它就是通过将底层的物理硬盘抽象的封装起来，然后以逻辑卷的方式呈现给上...', ' http://www.cnblogs.com/mchina/p/linux-centos-logical-volume-manager-lvm.html', '2014-06-18 10:47:00', 12582, 0),
(6, ' CentOS 6.3下配置软RAID（Software RAID）', ' 摘要: 一、RAID 简介RAID 是英文Redundant Array of Independent Disks 的缩写，翻译成中文意思是“独立磁盘冗余阵列”，有时也简称磁盘阵列（Disk Array）。简单的说，RAID是一种把多块独立的硬盘（物理硬盘）按不同的方式组合起来形成一个硬盘组（逻辑硬盘），从...', ' http://www.cnblogs.com/mchina/p/linux-centos-disk-array-software_raid.html', '2014-06-11 10:03:00', 10828, 0),
(7, ' 微信公众平台开发（十二） 发送客服消息', ' 摘要: 一、简介当用户主动发消息给公众号的时候（包括发送信息、点击自定义菜单、订阅事件、扫描二维码事件、支付成功事件、用户维权），微信将会把消息数据推送给开发者，开发者在一段时间内（目前修改为48小时）可以调用客服消息接口，通过POST一个JSON数据包来发送消息给普通用户，在48小时内不限制发送次数。此接...', ' http://www.cnblogs.com/mchina/p/3711217.html', '2014-05-06 16:02:00', 23092, 12),
(8, ' CentOS 6.3下rsync服务器的安装与配置', ' 摘要: 一、rsync 简介 Rsync（remote synchronize）是一个远程数据同步工具，可通过LAN/WAN快速同步多台主机间的文件，也可以使用 Rsync 同步本地硬盘中的不同目录。 Rsync 是用于取代rcp的一个工具，Rsync使用所谓的 “Rsync 算法” 来使本地和远程两个主机之间的文件达到同步，这个算法只传送两个文件的不同部分，而不是每次都整份传送，因此速度相当快。您可以参考How Rsync Works A Practical Overview进一步了解 rsync 的运作机制。 Rsync支持大多数的类Unix系统，无论是Linux、Solaris还是BSD上...', ' http://www.cnblogs.com/mchina/p/2829944.html', '2014-03-05 14:25:00', 20415, 0),
(9, ' 微信公众平台开发（十一） 功能整合', ' 摘要: 一、简介在前面的几篇微信功能开发文档中，各个微信的功能都是独立的，单一微信只能提供一种功能，这样不符合大众开发者和客户的需求。所以在这一篇文章中，我们将对前面开发出来的微信功能进行简单整合，以供读者参考。二、思路分析一种简单的做法是，截取关键字，然后进行判断，执行相应功能代码。这种做法比较适合功能不...', ' http://www.cnblogs.com/mchina/p/3494906.html', '2014-02-13 13:46:00', 16854, 6),
(10, ' 微信公众平台开发（十） 消息回复总结', ' 摘要: 一、简介微信公众平台提供了三种消息回复的格式，即文本回复、音乐回复和图文回复，在这一篇文章中，我们将对这三种消息回复的格式做一下简单讲解，然后封装成函数，以供读者使用。二、思路分析对于每一个POST请求，开发者在响应包中返回特定xml结构，对该消息进行响应（现支持回复文本、图文、语音、视频、音乐）。...', ' http://www.cnblogs.com/mchina/p/3364377.html', '2013-10-21 10:04:00', 55151, 33),
(11, ' 微信公众平台开发（九） 数据库操作', ' 摘要: 一、简介前面讲解的功能开发都是简单的调用API 完成的，没有对数据库进行操作。在接下来的高级功能开发中，需要使用到数据库，所以在这一篇中，将对MySQL 数据库的操作做一下简单的介绍，以供读者参考。二、思路分析百度开发者中心提供了强大的云数据库（包括MySQL, MongoDB, Redis），在这...', ' http://www.cnblogs.com/mchina/p/3332283.html', '2013-10-09 09:39:00', 44629, 16),
(12, ' 微信公众平台开发（八） 自定义菜单功能开发', ' 摘要: 一、简介微信公众平台服务号以及之前成功申请内测资格的订阅号都具有自定义菜单的功能。开发者可利用该功能为公众账号的会话界面底部增加自定义菜单，用户点击菜单中的选项，可以调出相应的回复信息或网页链接。自定义菜单接口将为公众账号的信息展示空间提供更多可能性。本文将针对自定义菜单做简单的开发应用，以供读者参...', ' http://www.cnblogs.com/mchina/p/3276878.html', '2013-08-26 09:34:00', 84443, 17),
(13, ' 微信公众平台开发（七） 聊天机器人功能开发', ' 摘要: 一、简介上一篇文章介绍了微信公众平台翻译功能的开发，实现了中、英、日语言互译，在实际生活中也能使用到。在接下来的这一篇文章中，我们将完成一个比较有趣的功能，那就是聊天机器人，可以在你无聊的时候陪你聊天逗你开心。二、思路分析在这个实验中，我们将调取小黄鸡官方（http://www.simsimi.co...', ' http://www.cnblogs.com/mchina/p/3271593.html', '2013-08-23 09:07:00', 22252, 11),
(14, ' 微信公众平台开发（六） 翻译功能开发', ' 摘要: 一、简介上一篇文章介绍了微信公众平台天气预报功能的开发，实现了微信公众平台的第一个实际应用，在接下来的这一篇文章中，我们将对微信翻译功能进行简单开发，以供读者参考。二、思路分析和上一篇查询天气的思路差不多，首先要对用户发送过来的消息进行判断，判断消息里是否含有“翻译”关键字，如果含有，则提取待翻译内...', ' http://www.cnblogs.com/mchina/p/3170565.html', '2013-07-29 10:49:00', 19453, 12),
(15, ' 微信公众平台开发（五） 天气预报功能开发', ' 摘要: 一、简介前面几篇文章对微信公众平台的开通及简单使用做了简单的介绍，但都没有涉及到实际使用中的问题，例如天气查询，公交查询，快递查询等。接下来的几篇文章将对实际生活中会经常使用到的一些功能进行开发讲解，以供读者参考。这一篇文章将对大家每天都会关心的天气查询进行开发，例如，用户发送消息 “苏州天气”，则...', ' http://www.cnblogs.com/mchina/p/3170551.html', '2013-07-12 10:40:00', 31103, 16),
(16, ' 微信公众平台开发（四） 简单回复功能开发', ' 摘要: 一、简介微信公众平台可以根据用户发送的信息进行判断，然后给出对应的回复，具有良好的交互性。下文将模拟简单的回复功能，根据这个案例，开发者也可以基本理解微信交互的原理，进行更深层次的开发。二、思路分析用户发送过来的文本信息，我们可以提取关键字，通过简单的 if...elseif...else... 实...', ' http://www.cnblogs.com/mchina/p/3155072.html', '2013-07-03 22:03:00', 22550, 22),
(17, ' 微信公众平台开发（三） 订阅事件（subscribe）处理', ' 摘要: 一、简介新用户关注微信公众平台，将产生一个订阅事件，即subscribe事件，默认代码中没有对这一事件进行相应回复处理。在新用户关注公众平台后，可能想知道该平台提供了哪些功能，以及怎样使用该平台，通俗一点讲就是该平台的“使用说明书”。本文将详细讲述对subscribe事件的处理过程，回复相应信息提升...', ' http://www.cnblogs.com/mchina/p/3120531.html', '2013-06-25 11:54:00', 42328, 11),
(18, ' 微信公众平台开发（二） 微信公众平台示例代码分析', ' 摘要: 一、摘要微信公众平台提供了一个简单的php示例代码，在做进一步开发之前，我们有必要将其详细了解一下。二、获取代码微信官网：http://mp.weixin.qq.com/mpres/htmledition/res/wx_sample.zip三、分析代码完整代码如下：valid();class wec...', ' http://www.cnblogs.com/mchina/archive/2013/06/07/3120592.html', '2013-06-07 14:21:00', 46906, 19),
(19, ' 微信公众平台开发（一） 配置接口', ' 摘要: 一、简介微信公众平台是腾讯公司在微信的基础上新增的功能模块，通过这一平台，个人和企业都可以打造一个微信的公众号，并实现和特定群体的文字、图片、语音的全方位沟通、互动。二、通讯机制三、注册微信平台公众帐号注册地址：https://mp.weixin.qq.com四、服务器端配置4.1 示例代码设置微信...', ' http://www.cnblogs.com/mchina/archive/2013/06/05/3108618.html', '2013-06-05 14:32:00', 172784, 61),
(20, ' PostgreSQL 角色管理', ' 摘要: 一、角色与用户的区别角色就相当于岗位：角色可以是经理，助理。用户就是具体的人：比如陈XX经理，朱XX助理，王XX助理。在PostgreSQL 里没有区分用户和角色的概念，&quot;CREATE USER&quot; 为 &quot;CREATE ROLE&quot; 的别名，这两个命令几乎是完全相同的，唯一的区别是&quot;CREATE USER&quot; 命令创建的用户默认带有LOGIN属性，而&quot;CREATE ROLE&quot; 命令创建的用户默认不带LOGIN属性(CREATE USERis equivalent toCREATE ROLEexcept thatCREAT', ' http://www.cnblogs.com/mchina/archive/2013/04/26/3040440.html', '2013-04-26 16:21:00', 4226, 0),
(21, ' MySQL 基础常用命令', ' 摘要: 一、启动与关闭1.1 Linux下启动mysql 的命令：a. rpm包安装：service mysqld startb. 源码包安装：/usr/local/mysql/bin/mysqld_safe --user=mysql &amp;1.2 Linux下重启mysql 的命令：a. rpm包安装：service mysqld restartb. 源码包安装：先关闭mysql/usr/local/mysql/bin/mysqladmin -uroot -p shutdown再启动mysql/usr/local/mysql/bin/mysqld_safe --user=mysql &amp;1', ' http://www.cnblogs.com/mchina/archive/2013/04/19/2571244.html', '2013-04-19 14:41:00', 6756, 0),
(22, ' PostgreSQL 查看数据库，索引，表，表空间大小', ' 摘要: 一、简介PostgreSQL 提供了多个系统管理函数来查看表，索引，表空间及数据库的大小，下面详细介绍一下。二、数据库对象尺寸函数函数名返回类型描述pg_column_size(any)int存储一个指定的数值需要的字节数（可能压缩过）pg_database_size(oid)bigint指定OID的数据库使用的磁盘空间pg_database_size(name)bigint指定名称的数据库使用的磁盘空间pg_indexes_size(regclass)bigint关联指定表OID或表名的表索引的使用总磁盘空间pg_relation_size(relation regclass, fork t', ' http://www.cnblogs.com/mchina/archive/2013/04/19/3028573.html', '2013-04-19 09:56:00', 4437, 1),
(23, ' PostgreSQL删除重复数据', ' 摘要: 去重的方法一般是找到重复数据中的一条，以某一唯一条件去掉其他重复值。Oracle去重的方法很多，常用的是根据 rowid 进行去重。PostgreSQL 库如何去除单表重复数据呢？可以通过 ctid 进行，下面是实验过程。一、创建测试表david=# create table emp (david(# id int,david(# name varchar);CREATE TABLEdavid=# 二、插入测试数据david=# insert into emp values (1, &#39;david&#39;);INSERT 0 1david=# insert into emp value', ' http://www.cnblogs.com/mchina/archive/2013/04/15/3022086.html', '2013-04-15 14:47:00', 1383, 0),
(24, ' PostgreSQL的时间/日期函数使用', ' 摘要: PostgreSQL的常用时间函数使用整理如下：一、获取系统时间函数1.1 获取当前完整时间select now();david=# select now(); now ------------------------------- 2013-04-12 15:39:40.399711+08(1 row)david=# current_timestamp 同 now() 函数等效。david=# select current_timestamp; now ------------------...', ' http://www.cnblogs.com/mchina/archive/2013/04/15/3010418.html', '2013-04-15 11:56:00', 30164, 0),
(25, ' PostgreSQL 序列（SEQUENCE）', ' 摘要: 一、简介序列对象（也叫序列生成器）就是用CREATE SEQUENCE 创建的特殊的单行表。一个序列对象通常用于为行或者表生成唯一的标识符。二、创建序列方法一：直接在表中指定字段类型为serial 类型david=# create table tbl_xulie (david(# id serial,david(# name text);NOTICE: CREATE TABLE will create implicit sequence &quot;tbl_xulie_id_seq&quot; for serial column &quot;tbl_xulie.id&quot;CREATE T', ' http://www.cnblogs.com/mchina/archive/2013/04/10/3012493.html', '2013-04-10 15:52:00', 14454, 0),
(26, ' PostgreSQL分区表（Table Partitioning）应用', ' 摘要: 一、简介 在数据库日渐庞大的今天，为了方便对数据库数据的管理，比如按时间，按地区去统计一些数据时，基数过于庞大，多有不便。很多商业数据库都提供分区的概念，按不同的维度去存放数据，便于后期的管理，PostgreSQL也不例外。 PostgresSQL分区的意思是把逻辑上的一个大表分割成物理上的几块儿。分区不仅能带来访问速度的提升，关键的是，它能带来管理和维护上的方便。 分区的具体好处是：某些类型的查询性能可以得到极大提升。更新的性能也可以得到提升，因为表的每块的索引要比在整个数据集上的索引要小。如果索引不能全部放在内存里，那么在索引上的读和写都会产生更多的磁盘访问。批量删除可以用简单的删除...', ' http://www.cnblogs.com/mchina/archive/2013/04/09/2973427.html', '2013-04-09 11:14:00', 10585, 4),
(27, ' PostgreSQL的generate_series函数应用', ' 摘要: 一、简介PostgreSQL 中有一个很有用处的内置函数generate_series，可以按不同的规则产生一系列的填充数据。二、语法函数参数类型返回类型描述generate_series(start, stop) int 或 bigint setof int 或 setof bigint(与参数类型相同) 生成一个数值序列，从start 到 stop，步进为一generate_series(start, stop, step) int 或 bigintsetof int 或 setof bigint(与参数类型相同) 生成一个数值序列，从start 到 stop，步进为stepgenerat', ' http://www.cnblogs.com/mchina/archive/2013/04/03/2997722.html', '2013-04-03 14:50:00', 1949, 1),
(28, ' Linux 配置双机SSH信任', ' 摘要: 一、实现原理使用一种被称为&quot;公私钥&quot;认证的方式来进行ssh登录。&quot;公私钥&quot;认证方式简单的解释是：首先在客户端上创建一对公私钥（公钥文件：~/.ssh/id_rsa.pub；私钥文件：~/.ssh/id_rsa），然后把公钥放到服务器上（~/.ssh/authorized_keys），自己保留好私钥。当ssh登录时，ssh程序会发送私钥去和服务器上的公钥做匹配。如果匹配成功就可以登录了。二、实验环境A机：TS-DEV/10.0.0.163B机：CS-DEV/10.0.0.188三、Linux/Unix双机建立信任3.1 在A机生成证书在A机root用户下执', ' http://www.cnblogs.com/mchina/archive/2013/03/15/2956017.html', '2013-03-15 16:48:00', 9921, 1),
(29, ' Linux下取代top的进程管理工具 htop', ' 摘要: 一、htop 简介This is htop, an interactive process viewer for Linux. It is a text-mode application (for console or X terminals) and requires ncurses.Comparison between htop and topIn &#39;htop&#39; you can scroll the list vertically and horizontally to see all processes and complete command lines.In &#39', ' http://www.cnblogs.com/mchina/archive/2013/03/15/2858041.html', '2013-03-15 09:02:00', 25214, 1),
(30, ' The Linux Pub Quiz answers', ' 摘要: 这是测试题答案，请先做测试题目，请点击这里查看题目。这就是测试题答案了，赶快算出你的分数，并在页面底部看看你的Linux水平如何吧！第一回合：人物1 – Larry Ewing 2 – William Nelson Joy(威廉&#183;纳尔逊&#183;乔伊)，通常人们称作Bill Joy(比尔&#183;乔伊) 3 – Mark Shuttleworth(马克&#183;沙特尔沃思)，他领导着Canonical和Ubuntu 4 – Guido van Rossum 5 – Perl 6 – Postfix 7 – Eric Allman 8 – Andy Tanenbaum(台湾译作：', ' http://www.cnblogs.com/mchina/archive/2013/03/13/2922154.html', '2013-03-13 09:54:00', 870, 0),
(31, ' The Linux Pub Quiz', ' 摘要: How well do you know your free software people, apps and commands? Put yourself to the test and see just how much you know - we don&#39;t think even Linus Torvalds knows all these...你对自由软件的人物、应用程序和命令了解多少？ 请你用下面的题目做自我测试 – 我们不保证Linux之父林纳斯&#183;托瓦兹(Linux Torvalds)也能做对所有的题……第一回合：人物1) 谁绘制了Linux的吉祥物Tux的原型', ' http://www.cnblogs.com/mchina/archive/2013/03/12/2922101.html', '2013-03-12 21:11:00', 869, 4),
(32, ' CentOS 6.3(x86_64)下安装Oracle 10g R2', ' 摘要: 目 录一、硬件要求二、软件三、系统安装注意四、安装Oracle前的系统准备工作五、安装Oracle，并进行相关设置六、升级Oracle到patchset 10.2.0.4七、使用rlwrap调用sqlplus中历史命令一、硬件要求1、内存 &amp; swapMinimum: 1 GB of RAMReco...', ' http://www.cnblogs.com/mchina/archive/2013/03/08/2934473.html', '2013-03-08 13:39:00', 26508, 6),
(33, ' Linux下Nagios的安装与配置', ' 摘要: 一、Nagios简介 Nagios是一款开源的电脑系统和网络监视工具，能有效监控Windows、Linux和Unix的主机状态，交换机路由器等网络设置，打印机等。在系统或服务状态异常时发出邮件或短信报警第一时间通知网站运维人员，在状态恢复后发出正常的邮件或短信通知。 Nagios原名为NetSa...', ' http://www.cnblogs.com/mchina/archive/2013/02/20/2883404.html', '2013-02-20 11:52:00', 160429, 84),
(34, ' linux screen 命令详解', ' 摘要: 一、背景系统管理员经常需要SSH 或者telent 远程登录到Linux 服务器，经常运行一些需要很长时间才能完成的任务，比如系统备份、ftp 传输等等。通常情况下我们都是为每一个这样的任务开一个远程终端窗口，因为它们执行的时间太长了。必须等待它们执行完毕，在此期间不能关掉窗口或者断开连接，否则这个...', ' http://www.cnblogs.com/mchina/archive/2013/01/30/2880680.html', '2013-01-30 09:22:00', 119774, 8),
(35, ' CentOS yum 源的配置与使用', ' 摘要: 一、yum 简介 yum，是Yellow dog Updater, Modified 的简称，是杜克大学为了提高RPM 软件包安装性而开发的一种软件包管理器。起初是由yellow dog 这一发行版的开发者Terra Soft 研发，用python 写成，那时还叫做yup(yellow dog u...', ' http://www.cnblogs.com/mchina/archive/2013/01/04/2842275.html', '2013-01-04 14:01:00', 149649, 13),
(36, ' Linux NFS服务器的安装与配置', ' 摘要: 一、NFS服务简介 NFS 是Network File System的缩写，即网络文件系统。一种使用于分散式文件系统的协定，由Sun公司开发，于1984年向外公布。功能是通过网络让不同的机器、不同的操作系统能够彼此分享个别的数据，让应用程序在客户端通过网络访问位于服务器磁盘中的数据，是在类Unix...', ' http://www.cnblogs.com/mchina/archive/2013/01/03/2840040.html', '2013-01-03 17:21:00', 165354, 11),
(37, ' Linux下暴力破解工具Hydra详解', ' 摘要: 一、简介Number one of the biggest security holes are passwords, as every password security study shows. Hydra is a parallized login cracker which supports numerous protocols to attack. New modules are easy to add, beside that, it is flexible and very fast.Hydra was tested to compile on Linux, Windows/Cy', ' http://www.cnblogs.com/mchina/archive/2013/01/01/2840815.html', '2013-01-01 23:14:00', 42103, 4),
(38, ' Linux下显示IP地理位置信息的小工具-nali', ' 摘要: 一、简介 nali，名字取自中文“哪里”的拼音。nali包含一组命令行程序，其主要功能就是把一些网络工具的输出的IP字符串，附加上地理位置信息(使用纯真数据库QQWry.Dat)。例如74.125.128.104会变成74.125.128.104[美国 加利福尼亚州山景市谷歌公司]。查询是在本地进行，并不会进行联网查询，所以效率方面不会对原始命令产生什么影响。 目前包含以下几个命令：nalinali-dignali-nslookupnali-traceroutenali-tracepathnali-ping 使用这些命令的前提是，他们对应的命令必须存在。例如你要用nali-dig，必须保...', ' http://www.cnblogs.com/mchina/archive/2012/12/24/2831220.html', '2012-12-24 16:40:00', 8220, 2),
(39, ' CentOS 6.3下Samba服务器的安装与配置', ' 摘要: 一、简介 Samba是一个能让Linux系统应用Microsoft网络通讯协议的软件，而SMB是Server Message Block的缩写，即为服务器消息块 ，SMB主要是作为Microsoft的网络通讯协议，后来Samba将SMB通信协议应用到了Linux系统上，就形成了现在的Samba软件...', ' http://www.cnblogs.com/mchina/archive/2012/12/18/2816717.html', '2012-12-18 15:13:00', 103550, 26),
(40, ' CentOS 6.3下源码安装LAMP(Linux+Apache+Mysql+Php)环境', ' 摘要: 一、简介什么是LAMP LAMP是一种Web网络应用和开发环境，是Linux, Apache, MySQL, Php/Perl的缩写，每一个字母代表了一个组件，每个组件就其本身而言都是在它所代表的方面功能非常强大的组件。 LAMP这个词的由来最早始于德国杂志“c&#39;t Magazine”，Mich...', ' http://www.cnblogs.com/mchina/archive/2012/11/28/2778779.html', '2012-11-28 15:05:00', 22651, 4),
(41, ' Linux Oracle服务启动&amp;停止脚本与开机自启动', ' 摘要: 在CentOS 6.3下安装完Oracle 10g R2，重开机之后，你会发现Oracle没有自行启动，这是正常的，因为在Linux下安装Oracle的确不会自行启动，必须要自行设定相关参数，首先先介绍一般而言如何启动oracle。一、在Linux下启动Oracle登录到CentOS，切换到oracle用户权限# su – oracle接着输入：$ sqlplus &quot;/as sysdba&quot;原本的画面会变为SQL&gt;接着请输入SQL&gt; startup就可以正常的启动数据库了。另外停止数据库的指令如下：SQL&gt; shutdown immediate二、检查Ora', ' http://www.cnblogs.com/mchina/archive/2012/11/27/2782993.html', '2012-11-27 15:35:00', 62390, 4),
(42, ' CentOS 6.3(x86_32)下安装Oracle 10g R2', ' 摘要: 一、硬件要求1、内存 &amp; swapMinimum: 1 GB of RAMRecommended: 2 GB of RAM or more检查内存情况# grep MemTotal /proc/meminfo# grep SwapTotal /proc/meminfo2、硬盘由于CentOS安装后差...', ' http://www.cnblogs.com/mchina/archive/2012/11/06/2737472.html', '2012-11-06 14:07:00', 24338, 3),
(43, ' Oracle笔记（十六） 数据库设计范式', ' 摘要: 数据库设计范式是一个很重要的概念，但是这个重要程度只适合于参考。使用数据库设计范式，可以让数据表更好的进行数据的保存，因为再合理的设计，如果数据量一大也肯定会存在性能上的问题。所以在开发之中，唯一可以称为设计的宝典 —— 设计的时候尽量避免日后的程序出现多表关联查询。一、第一范式所谓的第一范式指的就是数据表中的数据列不可再分。例如，现在有如下一张数据表：CREATE TABLE member ( mid NUMBER PRIMARY KEY, name VARCHAR2(200) NOT NULL, contact VARCHAR2(200));这个时候设计的就不合理，因为联系方式由多种...', ' http://www.cnblogs.com/mchina/archive/2012/09/13/2678094.html', '2012-09-13 09:48:00', 3361, 8),
(44, ' Oracle笔记（十五） 数据库备份', ' 摘要: 数据库的备份操作是在整个项目运行中最重要的工作之一。一、数据的导出和导入数据的导出和导入是针对于一个用户的备份操作，可以按照如下的方式完成：1、 数据的导出在硬盘上建立一个文件夹：c:ackup；输入exp指令；输入用户名和密码；设置导出文件的名称：导出文件: EXPDAT.DMP；2、 数据的导入先将表删除干净；进入到导出文件所在的文件夹之中：c:ackup；输入imp指令；输入用户名和密码；导入整个导出文件 (yes/no): no &gt; yes但是以上的操作只是做为一个演示，因为这种备份操作本身只适合数据量小的情况，如果数据量较大的话，这种操作是会损耗性能的，而且时间也会很长', ' http://www.cnblogs.com/mchina/archive/2012/09/12/2678093.html', '2012-09-12 16:04:00', 8669, 3),
(45, ' Oracle笔记（十四） 用户管理', ' 摘要: SQL语句分为三类：DML、DDL、DCL，之前已经讲解完了DML和DDL，现在就差DCL操作的，DCL主要表示的是数据库的控制语句，控制的就是操作权限，而在DCL之中，主要有两个语法：GRANT、REVOKE；权限的操作基础是需要有用户的，而这个时候就需要通过一个新的用户进行演示，而要想创建新用户则首先必须是具备管理员权限的sys、system两个用户操作。范例：创建一个dog用户，密码为wangwangCONN sys/change_on_install AS SYSDBA;CREATE USER dog IDENTIFIED BY wangwang;此时一个新的用户就创建完成了。注意：“', ' http://www.cnblogs.com/mchina/archive/2012/09/12/2678091.html', '2012-09-12 12:38:00', 2973, 0),
(46, ' Oracle笔记（十三） 视图、同义词、索引', ' 摘要: 一、视图在之前所学习过的所有的SQL语法之中，查询操作是最麻烦的，如果程序开发人员将大量的精力都浪费在查询的编写上，则肯定影响代码的工作进度，所以一个好的数据库设计人员，除了根据业务的操作设计出数据表之外，还需要为用户提供若干个视图，而每一个视图包装了一条条复杂的SQL语句，视图的创建语法如下：CREATE [OR REPLACE] VIEW 视图名称 AS 子查询;范例：创建一张视图CREATE VIEW myview AS SELECT d.deptno,d.dname,d.loc,COUNT(e.empno) count,AVG(e.sal) avg FROM emp e,dept...', ' http://www.cnblogs.com/mchina/archive/2012/09/11/2678090.html', '2012-09-11 19:37:00', 2838, 0),
(47, ' Oracle笔记（十二） 集合、序列', ' 摘要: 一、集合在数学的操作之中存在交、差、并、补的概念，而在数据的查询中也存在此概念，有如下几个连接符号：UNION：连接两个查询，相同的部分不显示；UNION ALL：连接两个查询，相同的部分显示；INTERSECT：返回两个查询中的相同部分；MINUS：返回两个查询中的不同部分；为了验证以上的操作，下面创建一张只包含20部门雇员信息的表：CREATE TABLE emp20 AS SELECT * FROM emp WHERE deptno=20;范例：验证UNIONSELECT * FROM emp UNIONSELECT * FROM emp20;范例：验证UNION ALLSELECT .', ' http://www.cnblogs.com/mchina/archive/2012/09/11/2678087.html', '2012-09-11 16:06:00', 2683, 3),
(48, ' Oracle笔记（十一） 建表、更新、查询综合练习', ' 摘要: 有某个学生运动会比赛信息的数据库，保存了如下的表：运动员sporter（运动员编号sporterid，运动员姓名name，运动员性别sex，所属系号department）项目item（项目编号itemid，项目名称itemname，项目比赛地点location）成绩grade（运动员编号id，项目编号itemid，积分mark）请用SQL语句完成如下功能：1、 建表，并在相应字段上增加约束；定义各个表的主键和外键约束；运动员的姓名和所属系别不能为空；积分要第为空值，要么为6，4，2，0，分别代表第一，二，三名和其他名次的积分，注意名次可以有并列名次，后面的排名不往前提升，例如，如果有两个并列第', ' http://www.cnblogs.com/mchina/archive/2012/09/11/2667984.html', '2012-09-11 11:51:00', 3948, 3),
(49, ' Oracle笔记（十） 约束', ' 摘要: 表虽然建立完成了，但是表中的数据是否合法并不能有所检查，而如果要想针对于表中的数据做一些过滤的话，则可以通过约束完成，约束的主要功能是保证表中的数据合法性，按照约束的分类，一共有五种约束：非空约束、唯一约束、主键约束、检查约束、外键约束。一、非空约束（NOT NULL）：NK当数据表中的某个字段上的内容不希望设置为null的话，则可以使用NOT NULL进行指定。范例：定义一张数据表DROP TABLE member PURGE;CREATE TABLE member( mid NUMBER, name VARCHAR2(50) NOT NULL);因为此时存在了“NOT NULL...', ' http://www.cnblogs.com/mchina/archive/2012/09/10/2653423.html', '2012-09-10 17:23:00', 4114, 3),
(50, ' Oracle笔记（九） 表的创建及管理', ' 摘要: 对于数据库而言实际上每一张表都表示的是一个数据库的对象，而数据库对象指的就是DDL定义的所有操作，例如：表、视图、索引、序列、约束等等，都属于对象的操作，所以表的建立就是对象的建立，而对象的操作主要分为以下三类语法：创建对象：CREATE 对象名称 …；删除对象：DROP 对象名称 …；修改对象：ALTER 对象名称 …；一、常用的数据字段每一张数据表实际上都是由若干个字段所组成，而每一个字段都会有其对应的数据类型，而在Oracle之中，常用的数据类型有如下几种：№数据类型关键字描述1字符串VARCHAR2(n)其中n表示的是字符串所能保存的最大长度，基本上保存200个左右的内容2整数NUMB', ' http://www.cnblogs.com/mchina/archive/2012/09/10/2653420.html', '2012-09-10 10:54:00', 2685, 2),
(51, ' Oracle笔记（八） 复杂查询及总结', ' 摘要: 一、复杂查询1、 列出至少有一个员工的所有部门编号、名称，并统计出这些部门的平均工资、最低工资、最高工资。1、确定所需要的数据表：emp表：可以查询出员工的数量；dept表：部门名称；emp表：统计信息；2、确定已知的关联字段：emp.deptno=dept.deptno； 第一步：找出至少有一个员工的部门编号SELECT deptno,COUNT(empno)FROM empGROUP BY deptnoHAVING COUNT(empno)&gt;1;第二步：找到部门名称，肯定使用部门表，因为现在的数据量较小，所以可以将之前的emp表和dept表两个进行连接，统一采用多字段分组的方式查询；', ' http://www.cnblogs.com/mchina/archive/2012/09/09/2653417.html', '2012-09-09 21:02:00', 5022, 1),
(52, ' Oracle笔记（七） 数据更新、事务处理、数据伪列', ' 摘要: 一、数据的更新操作DML操作语法之中，除了查询之外还有数据的库的更新操作，数据的更新操作主要指的是：增加、修改、删除数据，但是考虑到emp表以后还要继续使用，所以下面先将emp表复制一份，输入如下指令：CREATE TABLE myemp AS SELECT * FROM emp;这种语法是Oracle中支持的操作，其他数据库不一样。1、数据增加如果现在要想实现数据的增加操作，则可以使用如下的语法完成：INSERT INTO 表名称 [(字段1,字段2,…)] VALUES(值1,值2,…);如果要想进行增加数据的话，则以下的几种数据类型要分别处理：增加数字：直接编写数字，例如：123；增加字', ' http://www.cnblogs.com/mchina/archive/2012/09/08/2651647.html', '2012-09-08 22:28:00', 4439, 8),
(53, ' Oracle笔记（六） 多表查询', ' 摘要: 本次预计讲解的知识点1、 多表查询的操作、限制、笛卡尔积的问题；2、 统计函数及分组统计的操作；3、 子查询的操作，并且结合限定查询、数据排序、多表查询、统计查询一起完成各个复杂查询的操作；一、多表查询的基本概念在之前所使用的查询操作之中，都是从一张表之中查询出所需要的内容，那么如果现在一个查询语句需要显示多张表的数据，则就必须应用到多表查询的操作，而多表查询的语法如下：SELECT [DISTINCT] * | 字段 [别名] [,字段 [别名] ,…]FROM 表名称 [别名], [表名称 [别名] ,…][WHERE 条件(S)][ORDER BY 排序字段 [ASC|DESC] [,排', ' http://www.cnblogs.com/mchina/archive/2012/09/07/2651568.html', '2012-09-07 16:15:00', 30926, 21),
(54, ' Oracle笔记（五） 单行函数', ' 摘要: 虽然各个数据库都是支持SQL语句的，但是每一个数据库也有每一个数据库自己所支持的操作函数，这些就是单行函数，而如果要想进行数据库开发的话，除了要会使用SQL之外 ，就是要多学习函数。单行函数主要分为以下五类：字符函数、数字函数、日期函数、转换函数、通用函数；一、字符函数字符函数的功能主要是进行字符串数据的操作，下面给出几个字符函数：UPPER(字符串 | 列)：将输入的字符串变为大写返回；LOWER(字符串 | 列)：将输入的字符串变为小写返回；INITCAP(字符串 | 列)：开头首字母大写；LENGTH(字符串 | 列)：求出字符串的长度；REPLACE(字符串 | 列)：进行替换；SUB', ' http://www.cnblogs.com/mchina/archive/2012/09/07/2649975.html', '2012-09-07 12:41:00', 5238, 5),
(55, ' Oracle笔记（四） 简单查询、限定查询、数据的排序', ' 摘要: 一、简单查询SQL（Structured Query Language) 结构化查询语言，是一种数据库查询和程序设计语言，用于存取数据以及查询、更新和管理关系数据库系统。ANSI（美国国家标准学会）声称，SQL是关系数据库管理系统的标准语言。Oracle数据库之所以发展的很好，主要也是因为Oracle是全世界最早采用SQL语句的数据库产品。SQL功能强大，概括起来，它可以分成以下几组：DML（Data Manipulation Language） 数据操作语言，用于检索或者修改数据DDL（Data Definition Language） 数据定义语言，用于定义数据的结构，创建、修改或者删除数', ' http://www.cnblogs.com/mchina/archive/2012/09/07/2633735.html', '2012-09-07 09:33:00', 4939, 3),
(56, ' Oracle笔记（三） Scott用户的表结构', ' 摘要: 在Oracle的学习之中，重点使用的是SQL语句，而所有的SQL语句都要在scott用户下完成，这个用户下一共有四张表，可以使用：SELECT * FROM tab;查看所有的数据表的名称，如果现在要想知道每张表的表结构，则可以采用以下的命令完成：DESC 表名称；1、 部门表：dept№名称类型描述1DEPTNONUMBER(2)表示部门编号，由两位数字所组成2DNAMEVARCHAR2(14)部门名称，最多由14个字符所组成3LOCVARCHAR2(13)部门所在的位置2、 雇员表：emp№名称类型描述1EMPNONUMBER(4)雇员的编号，由四位数字所组成2ENAMEVARCHAR2(', ' http://www.cnblogs.com/mchina/archive/2012/09/06/2649951.html', '2012-09-06 23:06:00', 7458, 0),
(57, ' Oracle笔记（二） SQLPlus命令', ' 摘要: 对于Oracle数据库操作主要使用的是命令行方式，而所有的命令都使用sqlplus完成，对于sqlplus有两种形式。一种是dos风格的sqlplus：sqlplus.exe;另一种是windows风格的sqlplus：sqlplusw.exe;在Oracle 10g之中主要使用的是sqlplusw命令，因为其可以进行一些显示数据的调整。 此时会找到默认的已经可以使用的数据库实例。范例：输入查询指令SELECT * FROM emp;此时的数据已经可以正常的显示，但是依然会存在数据折行的问题，因为这个是默认的每行的数据大小，而现在可以通过两个命令进行调整：设置每行显示的记录长度：SET LIN', ' http://www.cnblogs.com/mchina/archive/2012/09/06/2633674.html', '2012-09-06 19:41:00', 5822, 3),
(58, ' Oracle笔记（一） Oracle简介及安装', ' 摘要: 一、轨迹二、Oracle简介 Oracle是现在全世界最大的数据库提供商，编程语言提供商，应用软件提供商，它的地位等价于微软的地位。 Oracle在古希腊神话中被称为“神谕”，指的是上帝的宠儿，在中国的商周时期，把一些刻在龟壳上的文字也称为上天的指示，所以在中国Oracle又翻译为甲骨文。 Oracle的公司发展最早起源于1970年6月IBM的一个技术员，埃德加&#183;考特(Edgar Frank Codd) 在Communications of ACM上发表的论文 —— 大型共享数据库数据的关系模型（A Relational Model of Data for Large Shared ', ' http://www.cnblogs.com/mchina/archive/2012/09/06/2634905.html', '2012-09-06 14:48:00', 5180, 14),
(59, ' CentOS 6.3下部署LVS(NAT)+keepalived实现高性能高可用负载均衡', ' 摘要: 一、简介VS/NAT原理图：二、系统环境实验拓扑：系统平台：CentOS 6.3Kernel：2.6.32-279.el6.i686LVS版本：ipvsadm-1.26keepalived版本：keepalived-1.2.4三、安装0、安装LVS前系统需要安装popt-static，kernel-devel，make，gcc，openssl-devel，lftp，libnl*，popt*1、在两台Director Server上分别配置LVS+KeepalivedLVS install -------------[root@CentOS-LVS_MASTER ~]# wget http://', ' http://www.cnblogs.com/mchina/archive/2012/08/27/2644391.html', '2012-08-27 13:49:00', 23499, 8),
(60, ' PostgreSQL学习手册(十七) PL/pgSQL过程语言', ' 摘要: 一、概述： PL/pgSQL函数在第一次被调用时，其函数内的源代码(文本)将被解析为二进制指令树，但是函数内的表达式和SQL命令只有在首次用到它们的时 候，PL/pgSQL解释器才会为其创建一个准备好的执行规划，随后对该表达式或SQL命令的访问都将使用该规划。如果在一个条件语句中，有部分SQL命 令或表达式没有被用到，那么PL/pgSQL解释器在本次调用中将不会为其准备执行规划，这样的好处是可以有效地减少为PL/pgSQL函数里的语句生成 分析和执行规划的总时间，然而缺点是某些表达式或SQL命令中的错误只有在其被执行到的时候才能发现。 由于PL/pgSQL在函数里为一个命令制定了执行计划，..', ' http://www.cnblogs.com/mchina/archive/2012/08/21/2541984.html', '2012-08-21 12:05:00', 680, 1),
(61, ' PostgreSQL学习手册(十六) SQL语言函数', ' 摘要: 一、基本概念： SQL函数可以包含任意数量的查询，但是函数只返回最后一个查询(必须是SELECT)的结果。在简单情况下，返回最后一条查询结果的第一行。如果最后 一个查询不返回任何行，那么该函数将返回NULL值。如果需要该函数返回最后一条SELECT语句的所有行，可以将函数的返回值定义为集合，即SETOF sometype。 SQL函数的函数体应该是用分号分隔的SQL语句列表，其中最后一条语句之后的分号是可选的。除非函数声明为返回void，否则最后一条语句必须是 SELECT。事实上，在SQL函数中，不仅可以包含SELECT查询语句，也可以包含INSERT、UPDATE和DELETE等其...', ' http://www.cnblogs.com/mchina/archive/2012/08/21/2537402.html', '2012-08-21 12:04:00', 575, 0),
(62, ' PostgreSQL学习手册(十五) 客户端命令', ' 摘要: 零、口令文件： 在给出其它PostgreSQL客户端命令之前，我们需要先介绍一下PostgreSQL中的口令文件。之所以在这里提前说明该文件，是因为我们在后面的示例代码中会大量应用该文件，从而保证我们的脚本能够自动化完成。换句话说，如果在客户端命令执行时没有提供该文件，PostgreSQL的所有客户端命令均会被口令输入提示中断。 在当前用户的HOME目录下，我们需要手工创建文件名为 .pgpass的口令文件，这样就可以在我们连接PostgreSQL服务器时，客户端命令自动读取该文件已获得登录时所需要的口令信息。该文件的格式如下： hostname:port:database:username:', ' http://www.cnblogs.com/mchina/archive/2012/08/21/2532338.html', '2012-08-21 12:03:00', 1820, 0),
(63, ' PostgreSQL学习手册(十四) 系统视图', ' 摘要: 一、pg_tables: 该视图提供了对有关数据库中每个表的有用信息地访问。名字类型引用描述schemanamenamepg_namespace.nspname包含表的模式名字。tablenamenamepg_class.relname表的名字。tableownernamepg_authid.rolname表的所有者的名字。tablespacenamepg_tablespace.spcname包含表的表空间名字(如果是数据库缺省，则为 NULL)。hasindexesboolpg_class.relhasindex如果表拥有(或者最近拥有)任何索引，则为真。hasrulesboolpg_cla', ' http://www.cnblogs.com/mchina/archive/2012/08/21/2537401.html', '2012-08-21 12:02:00', 454, 0),
(64, ' PostgreSQL学习手册(十三) 系统表', ' 摘要: 一、pg_class: 该系统表记录了数据表、索引(仍然需要参阅pg_index)、序列、视图、复合类型和一些特殊关系类型的元数据。注意：不是所有字段对所有对象类型都有意义。名字类型引用描述relnamename数据类型名字。relnamespaceoidpg_namespace.oid包含这个对象的名字空间(模式)的OI。reltypeoidpg_type.oid对应这个表的行类型的数据类型。relowneroidpg_authid.oid对象的所有者。relamoidpg_am.oid对于索引对象，表示该索引的类型(B-tree，hash)。relfilenodeoid对象存储在磁盘上的文', ' http://www.cnblogs.com/mchina/archive/2012/08/21/2532768.html', '2012-08-21 12:01:00', 804, 0),
(65, ' PostgreSQL学习笔记（十二） 数据库维护', ' 摘要: 一、恢复磁盘空间 在PostgreSQL中，使用delete和update语句删除或更新的数据行并没有被实际删除，而只是在旧版本数据行的物理地址上将该行的状态置为已删除或已过期。因此当数据表中的数据变化极为频繁时，那么在一段时间之后该表所占用的空间将会变得很大，然而数据量却可能变化不大。要解决该问题，需要定期对数据变化频繁的数据表执行VACUUM操作。 VACUUM命令存在两种形式，VACUUM和VACUUM FULL，它们之间的区别见如下表格：无VACUUMVACUUMVACUUM FULL删除大量数据之后只是将删除数据的状态置为已删除，该空间不能记录被重新使用。如果删除的记录位于表的末..', ' http://www.cnblogs.com/mchina/archive/2012/08/21/2532780.html', '2012-08-21 12:00:00', 517, 0),
(66, ' PostgreSQL学习手册(十一) 数据库管理', ' 摘要: 一、概述： 数据库可以被看成是SQL对象(数据库对象)的命名集合，通常而言，每个数据库对象(表、函数等)只属于一个数据库。不过对于部分系统表而言，如 pg_database，是属于整个集群的。更准确地说，数据库是模式的集合，而模式包含表、函数等SQL对象。因此完整的对象层次应该是这样的：服务器、数据库、模式、表或其他类型的对象。 在与数据库服务器建立连接时，该连接只能与一个数据库形成关联，不允许在一个会话中进行多个数据库的访问。如以postgres用户登录，该用户可以访问的缺省数据库为postgres，在登录后如果执行下面的SQL语句将会收到PostgreSQL给出的相关错误信息。 po...', ' http://www.cnblogs.com/mchina/archive/2012/08/21/2532952.html', '2012-08-21 12:00:00', 269, 0),
(67, ' PostgreSQL学习手册(十) 角色和权限', ' 摘要: PostgreSQL是通过角色来管理数据库访问权限的，我们可以将一个角色看成是一个数据库用户，或者一组数据库用户。角色可以拥有数据库对象，如表、索引，也可以把这些对象上的权限赋予其它角色，以控制哪些用户对哪些对象拥有哪些权限。 一、数据库角色： 1. 创建角色： CREATE ROLE role_name; 2. 删除角色： DROP ROLE role_name; 3. 查询角色： 检查系统表pg_roles，如： SELECT rolname FROM pg_roles; 也可以在psql中执行du命令列出所有角色。 二、角色属性： 一个数据库角色可以有一系列属性，这些属性定义他的...', ' http://www.cnblogs.com/mchina/archive/2012/08/21/2532957.html', '2012-08-21 11:59:00', 432, 0),
(68, ' PostgreSQL学习手册(九) 服务器配置', ' 摘要: 一、服务器进程的启动和关闭： 下面是pg_ctl命令的使用方法和常用选项，需要指出的是，该命令是postgres命令的封装体，因此在使用上比直接使用postgres更加方便。 pg_ctl init[db] [-D DATADIR] [-s] [-o &quot;OPTIONS&quot;] pg_ctl start [-w] [-t SECS] [-D DATADIR] [-s] [-l FILENAME] [-o &quot;OPTIONS&quot;] pg_ctl stop [-W] [-t SECS] [-D DATADIR] [-s] [-m SHUTDOWN-MODE] pg_c', ' http://www.cnblogs.com/mchina/archive/2012/08/11/2532954.html', '2012-08-11 15:21:00', 458, 0),
(69, ' PostgreSQL学习手册(八) 性能提升技巧', ' 摘要: 一、使用EXPLAIN： PostgreSQL为每个查询都生成一个查询规划，因为选择正确的查询路径对性能的影响是极为关键的。PostgreSQL本身已经包含了一个规划器用于寻找最优规划，我们可以通过使用EXPLAIN命令来查看规划器为每个查询生成的查询规划。 PostgreSQL中生成的查询规划是由1到n个规划节点构成的规划树，其中最底层的节点为表扫描节点，用于从数据表中返回检索出的数据行。然而，不同的扫描节点类型代表着不同的表访问模式，如：顺序扫描、索引扫描，以及位图索引扫描等。如果查询仍然需要连接、聚集、排序，或者是对原始行的其它操作，那么就会在扫描节点&quot;之上&quot;有其它额', ' http://www.cnblogs.com/mchina/archive/2012/08/11/2537393.html', '2012-08-11 14:37:00', 1095, 0),
(70, ' PostgreSQL学习手册(七) 事物隔离', ' 摘要: 在SQL的标准中事物隔离级别分为以下四种： 1. 读未提交(Read uncommitted) 2. 读已提交(Read committed) 3. 可重复读(Repeatable read) 4. 可串行化(Serializable) 然而PostgreSQL在9.1之前的版本中只是实现了其中两种，即读已提交和可串行化，如果在实际应用中选择了另外两种，那么PostgreSQL 将会自动向更严格的隔离级别调整。在PostgreSQL v9.1的版本中提供了三种实现方式，即在原有的基础上增加了可重复读。在这篇博客中我们将只是针对2)和4)进行说明和比较，因为在9.1中，3)和 4)的差别...', ' http://www.cnblogs.com/mchina/archive/2012/08/11/2537392.html', '2012-08-11 12:45:00', 353, 0),
(71, ' PostgreSQL学习手册(六) 索引', ' 摘要: 一、索引的类型： PostgreSQL提供了多种索引类型：B-Tree、Hash、GiST和GIN，由于它们使用了不同的算法，因此每种索引类型都有其适合的查询类型，缺省时，CREATE INDEX命令将创建B-Tree索引。 1. B-Tree: CREATE TABLE test1 ( id integer, content varchar ); CREATE INDEX test1_id_index ON test1 (id); B-Tree索引主要用于等于和范围查询，特别是当索引列包含操作符&quot; &lt;、&lt;=、=、&gt;=和&gt;&quot;作为查询条件时，Postg', ' http://www.cnblogs.com/mchina/archive/2012/08/11/2533021.html', '2012-08-11 12:44:00', 714, 0),
(72, ' PostgreSQL学习手册(五) 函数和操作符', ' 摘要: 一、逻辑操作符： 常用的逻辑操作符有：AND、OR和NOT。其语义与其它编程语言中的逻辑操作符完全相同。二、比较操作符： 下面是PostgreSQL中提供的比较操作符列表：操作符描述 &lt;小于 &gt;大于 &lt;=小于或等于 &gt;=大于或等于 =等于 !=不等于 比较操作符可以用于所有可以比较的数据类型。所有比较操作符都是双目操作符，且返回boolean类型。除了比较操作符以外，我们还可以使用BETWEEN语句，如： a BETWEEN x AND y 等效于 a &gt;= x AND a &lt;= y a NOT BETWEEN x AND y 等效于 a &lt; x OR', ' http://www.cnblogs.com/mchina/archive/2012/08/11/2537382.html', '2012-08-11 12:41:00', 4119, 0);
INSERT INTO `tbl_cnblogs_info` (`id`, `blog_title`, `blog_desc`, `blog_url`, `blog_post_time`, `blog_page_views`, `blog_commentcount`) VALUES
(73, ' PostgreSQL学习手册(四) 常用数据类型', ' 摘要: 一、数值类型： 下面是PostgreSQL所支持的数值类型的列表和简单说明：名字存储空间描述范围 smallint2 字节小范围整数-32768 到 +32767 integer4 字节常用的整数-2147483648 到 +2147483647 bigint8 字节大范围的整数-9223372036854775808 到 9223372036854775807 decimal变长用户声明精度，精确无限制 numeric变长用户声明精度，精确无限制 real4 字节变精度，不精确6 位十进制数字精度...', ' http://www.cnblogs.com/mchina/archive/2012/08/11/2532964.html', '2012-08-11 12:40:00', 484, 0),
(74, ' PostgreSQL学习手册(三) 表的继承和分区', ' 摘要: 一、表的继承： 这个概念对于很多已经熟悉其他数据库编程的开发人员而言会多少有些陌生，然而它的实现方式和设计原理却是简单易懂，现在就让我们从一个简单的例子开始吧。 1. 第一个继承表： CREATE TABLE cities ( --父表 name text, population float, altitude int ); CREATE TABLE capitals ( --子表 state char(2) ) INHERITS (cities); capitals表继承自cities表的所有属性。在PostgreSQL里，一个表可以从零个或多个其它表中继承属性，而且一个查询既可以引...', ' http://www.cnblogs.com/mchina/archive/2012/08/11/2536997.html', '2012-08-11 12:39:00', 502, 0),
(75, ' PostgreSQL学习手册(二) 模式(Schema)', ' 摘要: 一个数据库包含一个或多个命名的模式，模式又包含表。模式还包含其它命名的对象，包括数据类型、函数，以及操作符。同一个对象名可以在不同的模式里使用而不会导致冲突； 比如，schema1和myschema都可以包含叫做mytable的表。和数据库不同，模式不是严格分离的：一个用户可以访问他所连接的数据库中的任意模式中的对象，只要他有权限。 我们需要模式有以下几个主要原因： 1). 允许多个用户使用一个数据库而不会干扰其它用户。 2). 把数据库对象组织成逻辑组，让它们更便于管理。 3). 第三方的应用可以放在不同的模式中，这样它们就不会和其它对象的名字冲突。 1. 创建模式： CREATE SC..', ' http://www.cnblogs.com/mchina/archive/2012/08/11/2536962.html', '2012-08-11 12:37:00', 626, 0),
(76, ' PostgreSQL学习手册(一) 数据表', ' 摘要: 一、表的定义： 对于任何一种关系型数据库而言，表都是数据存储的最核心、最基础的对象单元。现在就让我们从这里起步吧。 1. 创建表： CREATE TABLE products ( product_no integer, name text, price numeric ); 2. 删除表： DROP TABLE products; 3. 创建带有缺省值的表： CREATE TABLE products ( product_no integer, name text, price numeric DEFAULT 9.99 --DEFAULT是关键字，其后的数值9.99是字段pri...', ' http://www.cnblogs.com/mchina/archive/2012/08/11/2535005.html', '2012-08-11 12:32:00', 1225, 0),
(77, ' Packet Tracer 5.3实验(十六) 网络设备系统升级', ' 摘要: 一、TFTP简介 TFTP（Trivial File Transfer Protocol,简单文件传输协议）是TCP/IP协议族中的一个用来在客户机与服务器之间进行简单文件传输的协议，提供不复杂、开销不大的文件传输服务。TFTP承载在UDP上，使用69号端口。提供不可靠的数据流传输服务，不提供存取授权与认证机制，使用超时重传方式来保证数据的到达。与FTP相 比，TFTP的大小要小的多。TFTP与FTP的区别1、TFTP --简单文件传输协议，udp，69；2、FTP --文件传输协议，tcp，20，21；3、TFTP传输速度比FTP快，但是相对没有FTP安全。二、TFTP实验环境 一台装有TF', ' http://www.cnblogs.com/mchina/archive/2012/07/25/2605720.html', '2012-07-25 22:20:00', 2209, 0),
(78, ' Packet Tracer 5.2实验(十五) 网络端口地址转换NAPT配置', ' 摘要: 一、实验目标理解NAT网络地址转换的原理及功能；掌握NAPT的配置，实现局域网访问互联网；二、实验背景公司办公网需要接入互联网，公司只向ISP申请了一条专线，该专线分配了一个公网IP地址，配置实现全公司的主机都能访问外网。三、技术原理NAT将网络划分为内部网络和外部网络两部分，局域网主机利用NAT访问网络时，是将局域网内部的本地地址转换为全局地址（互联网合法的IP地址）后转发数据包；NAT分为两种类型：NAT（网络地址转换）和NAPT（网络端口地址转换IP地址对应一个全局地址）。NAPT：使用不同的端口来映射多个内网IP地址到一个指定的外网IP地址，多对一。NAPT采用端口多路复用方式。内部网', ' http://www.cnblogs.com/mchina/archive/2012/07/24/2606821.html', '2012-07-24 22:57:00', 3345, 0),
(79, ' Packet Tracer 5.2实验(十四) 网络地址转换NAT配置', ' 摘要: 一、实验目标理解NAT网络地址转换的原理及功能；掌握静态NAT的配置，实现局域网访问互联网；二、实验背景公司欲发布WWW服务，现要求将内网Web服务器IP地址映射为全局IP地址，实现外部网络可访问公司内部Web服务器。三、技术原理网络地址转换NAT（Network Address Translation），被广泛应用于各种类型Internet接入方式和各种类型的网络中。原因很简单，NAT不仅完美解决了IP地址不足的问题，而且还能够有效地避免来自网络外部的攻击，隐藏并保护网络内部的计算机。默认情况下，内部IP地址是无法被路由到外网的，内部主机10.1.1.1要与外部internet通信，IP包到', ' http://www.cnblogs.com/mchina/archive/2012/07/23/2605682.html', '2012-07-23 22:32:00', 5734, 1),
(80, ' Packet Tracer 5.2实验(十三) 扩展IP访问控制列表配置', ' 摘要: 一、实验目标理解扩展IP访问控制列表的原理及功能；掌握编号的扩展IP访问控制列表的配置方法；二、实验背景分公司和总公司分别属于不同的网段，部门之间用路由器进行信息传递，为了安全起见，分公司领导要求部门主机只能访问总公司服务器的WWW服务，不能对其使用ICMP服务。三、技术原理访问列表中定义的典型规则主要有以下：源地址、目标地址、上层协议、时间区域；扩展IP访问列表（编号为100~199，2000~2699）使用以上四种组合来进行转发或阻断分组；可以根据数据包的源IP、目的IP、源端口、目的端口、协议来定义规则，进行数据包的过滤；扩展IP访问列表的配置包括以下两步：定义扩展IP访问列表将扩展IP', ' http://www.cnblogs.com/mchina/archive/2012/07/22/2603786.html', '2012-07-22 16:43:00', 2672, 2),
(81, ' Packet Tracer 5.2实验(十二) 标准IP访问控制列表配置', ' 摘要: 一、实验目标理解标准IP访问控制列表的原理及功能；掌握编号的标准IP访问控制列表的配置方法；二、实验背景公司的经理部、财务部和销售部分别属于不同的3个网段，三部门之间用路由器进行信息传递，为了安全起见，公司领导要求销售部不能对财务部进行访问，但经理部可以对财务部进行访问。三、技术原理ACLs的全称为接入控制列表（Access Control Lists），也称为访问列表（Access List），俗称为防火墙，在有的文档中还称之为包过滤。ACLs通过定义一些规则对网络设备接口上的数据报文进行控制：允许通过或丢弃，从而提高网络可管理性和安全性；IP ACL分为两种：标准IP访问列表和扩展IP访问', ' http://www.cnblogs.com/mchina/archive/2012/07/20/2601773.html', '2012-07-20 22:18:00', 4071, 3),
(82, ' Packet Tracer 5.2实验(十一) 路由器综合路由配置', ' 摘要: 一、实验目标掌握综合路由的配置方法；掌握查看通过路由重分布学习产生的路由；熟悉广域网线缆的连接方式；二、实验背景假设某公司通过一台三层交换机连到公司出口路由器R1上，路由器R1再和公司外的另一台路由器R2连接。三层与R1间运行RIPv2路由协议，R1与R2间运行OSPF路由协议。现要做适当配置，实现公司内部主机与公司外部主机之间的相互通信。三、技术原理为了支持本设备能够运行多个路由协议进程，系统软件提供路由信息从一个路由进程重分布到另外一个路由进程的功能。比如你可以将OSPF路由域的路由重新分布后通告RIP路由域中，也可以将RIP路由域的路由重新分布后通告到OSPF路由域中。路由的相互重分布可', ' http://www.cnblogs.com/mchina/archive/2012/07/20/2599961.html', '2012-07-20 21:10:00', 3036, 2),
(83, ' Packet Tracer 5.0实验(十) 路由器OSPF动态路由配置', ' 摘要: 一、实验目标掌握OSPF协议的配置方法；掌握查看通过动态路由协议OSPF学习产生的路由；熟悉广域网线缆的连接方式；二、实验背景假设某公司通过一台三层交换机连到公司出口路由器上，路由器再和公司外的另一台路由器连接。现要做适当配置，实现公司内部主机与公司外部主机之间的相互通信。为了简化网管的管理维护工作，公司决定采用OSPF协议实现互通。三、技术原理OSPF开放式最短路径优先协议，是目前网络中应用最广泛的路由协议之一。属于内部网关路由协议，能够适应各种规模的网络环境，是典型的链路状态协议。OSPF路由协议通过向全网扩散设备的链路状态信息，使网络中每台设备最终同步一个具有全网链路状态的数据库，然后路', ' http://www.cnblogs.com/mchina/archive/2012/07/18/2597856.html', '2012-07-18 17:51:00', 4840, 2),
(84, ' Packet Tracer 5.0实验(九) 路由器RIP动态路由配置', ' 摘要: 一、实验目标掌握RIP协议的配置方法；掌握查看通过动态路由协议RIP学习产生的路由；熟悉广域网线缆的连接方式；二、实验背景假设校园网通过一台三层交换机连到校园网出口路由器上，路由器再和校园外的另一台路由器连接。现要做适当配置，实现校园网内部主机与校园网外部主机之间的相互通信。为了简化网管的管理维护工作，学校决定采用RIP V2协议实现互通。三、技术原理RIP（Routing Information Protocols），路由信息协议，是应用较早、使用较普通的IGP内部网关协议，适用于小型同类网络，是距离矢量协议；RIP协议以跳数衡量路径开销，RIP协议里规定最大跳数为15；RIP协议有两个版本', ' http://www.cnblogs.com/mchina/archive/2012/07/18/2597618.html', '2012-07-18 16:11:00', 4273, 3),
(85, ' Packet Tracer 5.0实验(八) 路由器静态路由配置', ' 摘要: 一、实验目标掌握静态路由的配置方法和技巧；掌握通过静态路由方式实现网络的连通性；熟悉广域网线缆的连接方式；二、实验背景学校有新旧两个校区，每个校区是一个独立的局域网，为了使新旧校区能够正常相互通讯，共享资源，每个校区出口利用一台路由器进行连接，两台路由器间学校申请了一条2M的DDN专线进行相连，要求你做适当配置实现两个校区间的正常相互访问。三、技术原理路由器属于网络层设备，能够根据IP包头的信息，选择一条最佳路径将数据包转发出去，实现不同网段的主机之间的互相访问。路由器是根据路由表进行选路和转发的，而路由表就是由一条条路由信息组成。生成路由表主要有两种方法：手工配置和动态配置，即静态路由协议配', ' http://www.cnblogs.com/mchina/archive/2012/07/18/2596515.html', '2012-07-18 14:19:00', 5352, 3),
(86, ' Packet Tracer 5.0实验(七) 路由器单臂路由配置', ' 摘要: 一、实验目标掌握单臂路由配置方法；通过单臂路由实现不同VLAN间互相通信；二、实验背景某企业有两个主要部门：技术部和销售部，分处于不同的办公室，为了安全和便于管理，对两个部门的主机进行了VLAN的划分，技术部和销售部分处于不同的VLAN。现由于业务的需求，需要销售部和技术部的主机能够相互访问，获得相应的资源，两个部门的交换机通过一台路由器进行了连接。三、技术原理单臂路由：是为实现VLAN间通信的三层网络设备路由器，它只需要一个以太接口，通过创建子接口可以承担所有VLAN的网关，而在不同的VLAN间转发数据。四、实验步骤实验拓扑1、当交换机设置成两个vlan时，逻辑上已经成为两个网络，广播被隔离', ' http://www.cnblogs.com/mchina/archive/2012/07/17/2595659.html', '2012-07-17 18:02:00', 3924, 4),
(87, ' Packet Tracer 5.0实验(六) 路由器基本配置', ' 摘要: 一、实验目标掌握路由器几种常用配置方法；掌握采用Console线缆配置路由器的方法；掌握采用telnet方式配置路由器的方法；熟悉路由器不同的命令行操作模式以及各种模式之间的切换；掌握路由器的基本配置命令；二、技术原理路由器的管理方式基本分为两种：带内管理和带外管理。通过路由器的Console口管理路由器属于带外管理，不占用路由器的网络接口，其特点是需要使用配置线缆，近距离配置。第一次配置时必须利用Console端口进行配置。三、实验步骤实验拓扑1、用标准console线缆连接计算机的串口和路由器的console口，在计算机上启用超级终端，并配置超级终端的参数，使计算机与路由器通过consol', ' http://www.cnblogs.com/mchina/archive/2012/07/16/2592814.html', '2012-07-16 22:30:00', 6293, 0),
(88, ' Packet Tracer 5.0实验(五) 快速生成树配置', ' 摘要: 一、实验目标理解生成树协议工作原理；掌握快速生成树协议RSTP基本配置方法；二、实验背景学校为了开展计算机教学和网络办公，建立了一个计算机教室和一个校办公区，这两处的计算机网络通过两台交换机互相连接组成内部校园网，为了提高网络的可靠性，作为网络管理员，你要用2条链路将交换机互连，现要求在交换机上做适当的配置，使网络避免环路。三、技术原理生成树协议(spanning-tree)，作用是在交换网络中提供冗余备份链路，并且解决交换网络中的环路问题；生成树协议是利用SPA算法，在存在交换环路的网络中生成一个没有环路的树形网络。运用该算法将交换网络的冗余备份链路从逻辑上断开，当主链路出现故障时，能够自动', ' http://www.cnblogs.com/mchina/archive/2012/07/15/2591973.html', '2012-07-15 21:25:00', 6537, 1),
(89, ' Packet Tracer 5.0实验(四) 利用三层交换机实现VLAN间路由', ' 摘要: 一、实验目标掌握交换机Tag VLAN 的配置；掌握三层交换机基本配置方法；掌握三层交换机VLAN路由的配置方法；通过三层交换机实现VLAN间相互通信；二、实验背景某企业有两个主要部门，技术部和销售部，分处于不同的办公室，为了安全和便于管理，对两个部门的主机进行了VLAN的划分，技术部和销售部分处于不同的VLAN。现由于业务的需求，需要销售部和技术部的主机能够相互访问，获得相应的资源，两个部门的交换机通过一台三层交换机进行了连接。三、技术原理三层交换机具备网络层的功能，实现VLAN间相互访问的原理是：利用三层交换机的路由功能，通过识别数据包的IP地址，查找路由表进行选路转发。三层交换机利用直连', ' http://www.cnblogs.com/mchina/archive/2012/07/14/2591598.html', '2012-07-14 16:34:00', 10495, 6),
(90, ' Packet Tracer 5.0实验(三) 交换机划分VLAN配置', ' 摘要: 一、实验目标理解虚拟 LAN(VLAN)基本原理；掌握一般交换机按端口划分 VLAN的配置方法；掌握Tag VLAN配置方法。二、实验背景某一公司内财务部、销售部的PC通过2台交换机实现通信；要求财务部和销售部内的PC可以互通，但为了数据安全起见，销售部和财务部需要进行隔离，现要在交换机上做适当配置来实现这一目的。三、技术原理VLAN是指在一个物理网段内，进行逻辑的划分，划分成若干个虚拟局域网。VLAN最大的特性是不受物理位置的限制，可以进行灵活的划分。VLAN具备了一个物理网段所具备的特性。相同VLAN内的主机可以相互直接通信，不同VLAN间的主机之间互相访问必须经由路由设备进行转发。广播数', ' http://www.cnblogs.com/mchina/archive/2012/07/14/2591384.html', '2012-07-14 12:33:00', 8020, 5),
(91, ' Packet Tracer 5.0实验(二) 交换机的Telnet远程登录设置', ' 摘要: 一、实验目标 掌握采用telnet方式配置交换机的方法二、技术原理配置交换机的管理IP地址(计算机的IP地址与交换机管理IP地址在同一网段)；为telnet用户配置用户名和登录口令：Switch(config)#enble password xxxx //设置进入特权模式的密码；Switch(config-line)#password xxxx //可以设置通过console端口连接设备及telnet远程登录时所需要的密码。Switch(config)#line console 0Switch(config-line)#password xxxx //设置通过console端口连接设备的密码.', ' http://www.cnblogs.com/mchina/archive/2012/07/13/2590916.html', '2012-07-13 22:56:00', 6888, 1),
(92, ' Packet Tracer 5.0实验(一) 交换机的基本配置与管理', ' 摘要: 一、实验目标掌握交换机基本信息的配置与管理二、技术原理交换机的管理方式基本分为两种：带内管理和带外管理。通过交换机的Console端口管理交换机属于带外管理：这种管理方式不占用交换机的网络端口，第一次配置交换机必须利用Console端口进行配置。通过远程Telnet、拨号等方式属于带内管理。三、交换机的命令行操作模式主要包括：用户模式 Switch&gt;特权模式 Switch#全局配置模式 Switch(config)#端口模式 Switch(config-if)#四、实验步骤 1、实验拓扑2、交换机基本配置命令 a. 进入特权模式 Switch&gt;enable //en=enable ', ' http://www.cnblogs.com/mchina/archive/2012/07/13/2587174.html', '2012-07-13 16:05:00', 4740, 0),
(93, ' Linux Shell常用技巧(十二) Shell编程', ' 摘要: 二十三. Bash Shell编程: 1. 读取用户变量: read命令是用于从终端或者文件中读取输入的内建命令，read命令读取整行输入，每行末尾的换行符不被读入。在read命令后面，如果没有指定变量名，读取的数据将被自动赋值给特定的变量REPLY。下面的列表给出了read命令的常用方式： 命令格式 描述 read answer 从标准输入读取输入并赋值给变量answer。 read first last 从标准输入读取输入到第一个空格或者回车，将输入的第一个单词放到变量first中，并将该行其他的输入放在变量last中。 read 从标准输入读取一行并赋值给特定变量REP...', ' http://www.cnblogs.com/mchina/archive/2012/07/04/2575079.html', '2012-07-04 14:48:00', 3305, 0),
(94, ' Linux Shell常用技巧(十一) 交互式使用shell', ' 摘要: 二十二. 交互式使用Bash Shell: 1. 用set命令设置bash的选项: 下面为set主要选项的列表及其表述： 选项名 开关缩写 描述 allexport -a 打开此开关，所有变量都自动输出给子Shell。 noclobber -C 防止重定向时文件被覆盖。 noglob -d 在路径和文件名中，关闭通配符。 #打开该选项 /&gt; set -o allexport #等同于set -a #关闭该选项 /&gt; set +o allexport #等同于set +a #列出当前所有选项的当前值。 /&gt; set -o allexport off braceexpan...', ' http://www.cnblogs.com/mchina/archive/2012/07/03/2575002.html', '2012-07-03 16:48:00', 3702, 0),
(95, ' Linux Shell常用技巧(十) 管道组合', ' 摘要: 二十. 通过管道组合Shell命令获取系统运行数据: 1. 输出当前系统中占用内存最多的5条命令: #1) 通过ps命令列出当前主机正在运行的所有进程。 #2) 按照第五个字段基于数值的形式进行正常排序(由小到大)。 #3) 仅显示最后5条输出。 /&gt; ps aux | sort -k 5n | tail -5 stephen 1861 0.2 2.0 96972 21596 ? S Nov11 2:24 nautilus stephen 1892 0.0 0.4 102108 4508 ? S&lt;sl Nov11 0:00 /usr/bin/pulseaudio stephen 1', ' http://www.cnblogs.com/mchina/archive/2012/07/03/2574340.html', '2012-07-03 10:38:00', 3969, 0),
(96, ' Linux Shell常用技巧(九) 系统运行进程', ' 摘要: 十九. 和系统运行进程相关的Shell命令: 1. 进程监控命令(ps): 要对进程进行监测和控制，首先必须要了解当前进程的情况，也就是需要查看当前进程，而ps命令就是最基本同时也是非常强大的进程查看命令。使用该命令可以 确定有哪些进程正在运行和运行的状态、进程是否结束、进程有没有僵死、哪些进程占用了过多的资源等等。总之大部分信息都是可以通过执行该命令得到的。 ps命令存在很多的命令行选项和参数，然而我们最为常用只有两种形式，这里先给出与它们相关的选项和参数的含义： 选项 说明 a 显示终端上的所有进程，包括其他用户的进程。 u 以用户为主的格式来显示程序状况。 x 显示...', ' http://www.cnblogs.com/mchina/archive/2012/07/02/2573708.html', '2012-07-02 21:23:00', 2464, 0),
(97, ' Linux Shell常用技巧(八) 系统运行状况', ' 摘要: 十八. 和系统运行状况相关的Shell命令: 1. Linux的实时监测命令(watch): watch 是一个非常实用的命令，可以帮你实时监测一个命令的运行结果，省得一遍又一遍的手动运行。该命令最为常用的两个选项是-d和-n，其中-n表示间隔多少秒 执行一次&quot;command&quot;，-d表示高亮发生变化的位置。下面列举几个在watch中常用的实时监视命令： /&gt; watch -d -n 1 &#39;who&#39; #每隔一秒执行一次who命令，以监视服务器当前用户登录的状况 Every 1.0s: who Sat Nov 12 12:37:18 2011 stephe', ' http://www.cnblogs.com/mchina/archive/2012/07/02/2573124.html', '2012-07-02 16:08:00', 2543, 0),
(98, ' Linux Shell常用技巧(七) find xargs', ' 摘要: 十六. 文件查找命令find: 下面给出find命令的主要应用示例： /&gt; ls -l #列出当前目录下所包含的测试文件 -rw-r--r--. 1 root root 48217 Nov 12 00:57 install.log -rw-r--r--. 1 root root 37 Nov 12 00:56 testfile.dat -rw-r--r--. 1 root root 10530 Nov 11 23:08 test.tar.bz2 -rw-r--r--. 1 root root 183 Nov 11 08:02 users -rw-r--r--. 1 root root 2', ' http://www.cnblogs.com/mchina/archive/2012/07/02/2573313.html', '2012-07-02 16:07:00', 8592, 0),
(99, ' Linux Shell常用技巧(六) sort uniq tar split', ' 摘要: 十二. 行的排序命令sort: 1. sort命令行选项： 选项 描述 -t 字段之间的分隔符 -f 基于字符排序时忽略大小写 -k 定义排序的域字段，或者是基于域字段的部分数据进行排序 -m 将已排序的输入文件，合并为一个排序后的输出数据流 -n 以整数类型比较字段 -o outfile 将输出写到指定的文件 -r 倒置排序的顺序为由大到小，正常排序为由小到大 -u 只有唯一的记录，丢弃所有具有相同键值的记录 -b 忽略前面的空格 2. sort使用实例： 提示：在下面的输出结果中红色标注的为第一排序字段，后面的依次为紫、绿。 /&gt; sed ...', ' http://www.cnblogs.com/mchina/archive/2012/07/02/2573269.html', '2012-07-02 15:43:00', 1674, 0),
(100, ' Linux Shell常用技巧(五) awk编程', ' 摘要: 十一. awk编程: 1. 变量：在awk中变量无须定义即可使用，变量在赋值时即已经完成了定义。变量的类型可以是数字、字符串。根据使用的不同，未初始化变量的值为0或空白字符串&quot; &quot;，这主要取决于变量应用的上下文。下面为变量的赋值负号列表： 符号 含义 等价形式 = a = 5 a = 5 += a = a + 5 a += 5 -= a = a - 5 a -= 5 *= a = a * 5 a *= 5 /= a = a / 5 a /= 5 %= a = a % 5 a %= 5 ^= a = a ^ 5 a ^= 5 /&gt; awk &#39;$1 ~ /...', ' http://www.cnblogs.com/mchina/archive/2012/06/30/2571317.html', '2012-06-30 20:47:00', 4277, 0),
(101, ' Linux Shell常用技巧(四) awk', ' 摘要: 九. awk实用功能: 和sed一样，awk也是逐行扫描文件的，从第一行到最后一行，寻找匹配特定模板的行，并在这些行上运行“选择”动作。如果一个模板没有指定动作，这些匹配的行就被显示在屏幕上。如果一个动作没有模板，所有被动作指定的行都被处理。 1. awk的基本格式： /&gt; awk &#39;pattern&#39; filename /&gt; awk &#39;{action}&#39; filename /&gt; awk &#39;pattern {action}&#39; filename 具体应用方式分别见如下三个用例： /&gt; cat employees Tom Jon', ' http://www.cnblogs.com/mchina/archive/2012/06/30/2571308.html', '2012-06-30 20:42:00', 3098, 0),
(102, ' Linux Shell常用技巧(三) sed', ' 摘要: 八、流编辑器sed8.1 sed简介sed是stream editor的缩写，一种流编辑器，它一次处理一行内容。处理时，把当前处理的行存储在临时缓冲区中，称为“模式空间”（pattern space），接着用sed命令处理缓冲区中的内容，处理完成后，把缓冲区的内容送往屏幕。接着处理下一行，这样不断重复，直到文件末尾。文件内容并没有改变，除非你使用重定向存储输出。sed主要用来自动编辑一个或多个文件，简化对文件的反复操作，编写转换程序等。8.2 sed命令格式sed [nefri] &#39;command&#39; file(s)常用选项:-n 使用安静（silent）模式。在一般sed的用法', ' http://www.cnblogs.com/mchina/archive/2012/06/30/2570523.html', '2012-06-30 20:28:00', 7944, 0),
(103, ' Linux Shell常用技巧(二) grep', ' 摘要: 七.　grep家族: 1. grep退出状态： 0: 表示成功； 1: 表示在所提供的文件无法找到匹配的pattern； 2: 表示参数中提供的文件不存在。 见如下示例： /&gt; grep &#39;root&#39; /etc/passwd root:x:0:0:root:/root:/bin/bash operator:x:11:0:operator:/root:/sbin/nologin /&gt; echo $? 0 /&gt; grep &#39;root1&#39; /etc/passwd #用户root1并不存在 /&gt; echo $? 1 /&gt; grep &#39', ' http://www.cnblogs.com/mchina/archive/2012/06/29/2570187.html', '2012-06-29 16:48:00', 5477, 0),
(104, ' Linux Shell常用技巧(一) RE', ' 摘要: 一. 特殊文件: /dev/null和/dev/tty Linux系统提供了两个对Shell编程非常有用的特殊文件，/dev/null和/dev/tty。其中/dev/null将会丢掉所有写入它的数据，换句换说，当程序将数据写入到此文件时，会认为它已经成功完成写入数据的操作，但实际上什么事都没有做。如果你需要的是命令的退出状态，而非它的输出，此功能会非常有用，见如下Shell代码： /&gt; vi test_dev_null.sh #!/bin/bash if grep hello TestFile &gt; /dev/null then echo &quot;Found&quot; els', ' http://www.cnblogs.com/mchina/archive/2012/06/29/2570018.html', '2012-06-29 15:37:00', 5350, 0),
(105, ' Linux JDK升级', ' 摘要: 一、jdk1.4卸载Redhat Enterprise 5 中自带安装了jdk1.4，在安装jdk1.6前，把jdk1.4卸载：1. 首先查看系统自带的JDK版本：[root@linux ~]# java-versionjava version &quot;1.4.2&quot;gij (GNU libgcj) version 4.1.2 20080704 (Red Hat 4.1.2-48)Copyright (C) 2006 Free Software Foundation, Inc.This is free software; see the source for copying con', ' http://www.cnblogs.com/mchina/archive/2012/06/28/2567597.html', '2012-06-28 14:46:00', 11849, 2),
(106, ' Linux命令vi/vim', ' 摘要: 一、vi的基本概念基本上vi可以分为三种状态，分别是命令模式（command mode）、插入模式（Insert mode）和底行模式（last line mode），各模式的功能区分如下：a) 命令行模式command mode）控制屏幕光标的移动，字符、字或行的删除，移动复制某区段及进入Insert mode下，或者到 last line mode。b) 插入模式（Insert mode）只有在Insert mode下，才可以做文字输入，按「ESC」键可回到命令行模式。c) 底行模式（last line mode）将文件保存或退出vi，也可以设置编辑环境，如寻找字符串、列出行号……等。不过', ' http://www.cnblogs.com/mchina/archive/2012/06/14/2549058.html', '2012-06-14 11:36:00', 2973, 0),
(107, ' CentOS 6.3下PostgreSQL 的安装与配置', ' 摘要: 一、简介PostgreSQL 是一种非常复杂的对象-关系型数据库管理系统（ORDBMS），也是目前功能最强大，特性最丰富和最复杂的自由软件数据库系统。有些特性甚至连商业数据库都不具备。这个起源于伯克利（BSD）的数据库研究计划目前已经衍生成一项国际开发项目，并且有非常广泛的用户。二、系统环境系统平台...', ' http://www.cnblogs.com/mchina/archive/2012/06/06/2539003.html', '2012-06-06 23:27:00', 24246, 4),
(108, ' Fail2ban', ' 摘要: 一、简介Fail2ban可以监视你的系统日志，然后匹配日志的错误信息（正则式匹配）执行相应的屏蔽动作（一般情况下是防火墙），例如当有人在试探你的SSH、SMTP、FTP密码，只要达到你预设的次数，fail2ban就会调用防火墙屏蔽这个IP，而且可以发送e-mail通知系统管理员，是一款很实用、很强大的IP自动屏蔽工具！Fail2Ban scans log files like /var/log/pwdfail and bans IP that makes too many password failures. It updates firewall rules to reject the IP', ' http://www.cnblogs.com/mchina/archive/2012/06/01/2530953.html', '2012-06-01 17:12:00', 641, 0),
(109, ' PostgreSQL Hot Standby', ' 摘要: 一、简介 PostgreSQL数据库提供了类似Oracle的standby数据库的功能。PostgreSQL9.0 standby数据库在应用WAL日志的同时，也可以提供只读服务，这是PostgreSQL9.0中最激动人心的功能，这个功能在oracle数据库中也只是最新版本11g中才有的新功能。这个功能在oracle中叫active dataguard，在PostgreSQL中称为hot standby。在利用日志恢复数据的同时可以用只读的方式打开数据库，用户可以在备用数据库上进行查询、报表等操作，也可用做读写分离。在PostgreSQL9.0之前，也可以搭建standby数据库，但stand', ' http://www.cnblogs.com/mchina/archive/2012/05/26/2518350.html', '2012-05-26 16:19:00', 5921, 1),
(110, ' RHEL 5.4下部署LVS(DR)+keepalived实现高性能高可用负载均衡', ' 摘要: 一、简介LVS是Linux Virtual Server的简写，意即Linux虚拟服务器，是一个虚拟的服务器集群系统。本项目在1998年5月由章文嵩博士成立，是中国国内最早出现的自由软件项目之一。目前有三种IP负载均衡技术（VS/NAT、VS/TUN和VS/DR）；十种调度算法（rr|wrr|lc|wlc|lblc|lblcr|dh|sh|sed|nq）。Keepalived在这里主要用作RealServer的健康状态检查以及LoadBalance主机和BackUP主机之间failover的实现。LVS+Keepalived能实现的功能：利用LVS控制器主备模式避免单点故障以及自动删除故障WE', ' http://www.cnblogs.com/mchina/archive/2012/05/23/2514728.html', '2012-05-23 14:13:00', 7572, 1),
(111, ' 在Nginx中部署基于IP的虚拟主机', ' 摘要: 一、虚拟主机概念 虚拟主机是在网络服务器上划分出一定的磁盘空间供用户放置站点、应用组件等，提供必要的站点功能、数据存放和传输功能。所谓虚拟主机，也叫“网站空间”， 就是把一台运行在互联网上的服务器划分成多个“虚拟”的服务器，每一个虚拟主机都具有独立的域名和完整的Internet服务器（支持WWW、FTP、 E-mail等）功能，从用户角度来看，每台虚拟主机和一台独立的服务器完全相同，在IP地址日益紧张的今天，基于域名的虚拟主机要比基于IP的虚拟主机 使用的更加广泛。二、系统环境系统平台：RHEL 5.4Nginx版本：nginx-1.0.15三、配置基于IP的虚拟主机 Linux、FreeBS', ' http://www.cnblogs.com/mchina/archive/2012/05/21/2511824.html', '2012-05-21 20:08:00', 8284, 2),
(112, ' Linux下安装Tomcat', ' 摘要: 一、简介 Tomcat是一个免费的开源的Serlvet容器，它是Apache基金会的Jakarta项目中的一个核心项目，由Apache，Sun和 其它一些公司及个人共同开发而成。由于有了Sun的参与和支持，最新的Servlet和Jsp规范总能在Tomcat中得到体现。 Tomcat是稳固的独立的Web服务器与Servlet Container，不过，其Web服务器的功能则不如许多更健全的Web服务器完整，如Apache Web服务器(举例来说，Tomcat没有大量的选择性模块)。不过，Tomcat是自由的开源软件，而且有许多高手致力于其发展。 在安装Tomcat之前需要安装j2sdk(...', ' http://www.cnblogs.com/mchina/archive/2012/05/21/2511789.html', '2012-05-21 16:18:00', 5050, 0),
(113, ' Linux下安装Jboss', ' 摘要: 一、简介JBoss是一个运行EJB的J2EE应用服务器。它是开放源代码的项目，遵循最新的J2EE规范。从JBoss项目开始至今，它已经从一个EJB容器发展成为一个基于的J2EE的一个web 操作系统(operating system for web)，它体现了J2EE规范中最新的技术。无论是学习还是应用，JBoss为我们提供了一个非常优秀的平台。JBoss是一个管理EJB的容器和服务器，支持EJB 1.1、EJB 2.0和EJB3.0的规范。但JBoss核心服务不包括支持servlet/JSP的WEB容器，一般与Tomcat或Jetty绑定使用。 JBoss具有如下优点：1、JBoss是免费的', ' http://www.cnblogs.com/mchina/archive/2012/05/18/2507684.html', '2012-05-18 14:11:00', 12182, 1),
(114, ' LNMP(linux+nginx+mysql+php)服务器环境配置', ' 摘要: 一、简介 Nginx是俄罗斯人编写的十分轻量级的HTTP服务器,Nginx，它的发音为“engine X”， 是一个高性能的HTTP和反向代理服务器，同时也是一个IMAP/POP3/SMTP 代理服务器．Nginx是由俄罗斯人 Igor Sysoev为俄罗斯访问量第二的 Rambler.ru站点开发的，它已经在该站点运行超过三年了。Igor Sysoev在建立的项目时,使用基于BSD许可。 在高并发连接的情况下，Nginx是Apache服务器不错的替代品。Nginx同时也可以作为7层负载均衡服务器来使用。Nginx 0.8.46 + PHP 5.2.14 (FastCGI) 可以承受3万以..', ' http://www.cnblogs.com/mchina/archive/2012/05/17/2507102.html', '2012-05-17 23:56:00', 52676, 10),
(115, ' 构建基于Nginx的web服务器', ' 摘要: 一、简介Nginx(&quot;engine x&quot;) 是一个高性能的HTTP 和反向代理服务器，也是一个IMAP/POP3/SMTP代理服务器。 Nginx 是由Igor Sysoev为俄罗斯访问量第二的Rambler.ru站点开发的，它已经在该站点运行超过四年多了。Igor 将源代码以类BSD许可证的形式发布。自Nginx 发布四年来，Nginx 已经因为它的占有内存少、并发能力强、稳定性、丰富的功能集、示例配置文件和低系统资源的消耗而闻名了。目前国内各大门户网站已经部署了Nginx，如新浪、网易、腾讯等；国内几个重要的视频分享网站也部署了Nginx，如六房间、酷6等。新近发现Ng', ' http://www.cnblogs.com/mchina/archive/2012/04/25/2469680.html', '2012-04-25 13:43:00', 3617, 0);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
